#image:
#  repository: "yeecheeepam/libapi"
#  tag: "latest"

application:
  clientOriginUrl: "https://library-cru.xyz"

liquibase:
  enabled: true
  changeLog: "classpath:/db/changelog/db.changelog-master.yaml"

spring:
  applicationName: "libapi"
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://libapidb:5432/libapidb"
  jpa:
    hibernate:
      ddlAuto: "none"
      namingPhysicalStrategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    showSql: true

server:
  port: 6060

logging:
  level:
    liquibase: "DEBUG"

debug: true

web:
  resources:
    addMappings: false

security:
  oauth2:
    resourceserver:
      jwt:
        audiences: "https://api.library-cru.xyz/"
        issuerUri: "https://dev-xkl6rfiq0rmh5wfz.us.auth0.com/"